# Template de configuration des secrets pour Streamlit
# Copiez ce fichier vers .streamlit/secrets.toml et remplissez vos valeurs

[google]
# Configuration OAuth Google Drive
# Obtenez ces valeurs depuis Google Cloud Console
client_id = "your_google_client_id_here"
client_secret = "your_google_client_secret_here"

[openai]
# Clé API OpenAI (optionnel)
api_key = "your_openai_api_key_here"

[venice]
# Clé API Venice (fallback optionnel)
api_key = "your_venice_api_key_here"

# Instructions pour configurer Google OAuth:
# 1. Allez sur https://console.cloud.google.com/
# 2. Créez un nouveau projet ou sélectionnez un projet existant
# 3. Activez l'API Google Drive
# 4. Créez des identifiants OAuth 2.0
# 5. Ajoutez votre URL Streamlit comme URI de redirection autorisée
# 6. Copiez client_id et client_secret ici