
# Copy this to .streamlit/secrets.toml and fill in your actual values
# DO NOT commit this file to version control

[google_oauth]
client_id = "your-google-oauth-client-id.apps.googleusercontent.com"
client_secret = "your-google-oauth-client-secret"
redirect_uri = "https://your-app-name.streamlit.app/"

# Optional: AI service API keys
[ai_services]
openai_api_key = "your-openai-api-key"
venice_api_key = "your-venice-api-key"

# Optional: Other service keys
[services]
other_api_key = "your-other-service-key"
