# Template de configuration des secrets
# Copiez ce fichier vers secrets.toml et remplissez vos vraies clés

[google_oauth]
client_id = "VOTRE_GOOGLE_CLIENT_ID"
client_secret = "VOTRE_GOOGLE_CLIENT_SECRET"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
redirect_uris = ["http://localhost:8501"]

[openai]
api_key = "sk-proj-VOTRE_CLE_OPENAI"

[venice]
api_key = "VOTRE_CLE_VENICE_OPTIONNELLE"

[fileverse]
api_key = "VOTRE_CLE_FILEVERSE_OPTIONNELLE"